GuyKh/py-iec-api

pyproject.toml
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*
Please provide enough information so that others can review your pull request:
Explain the **details** for making this change. What existing problem does the pull request solve?
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
=> Change required python version to 3.9

.pre-commit-config.yaml, pyproject.toml
Add pre-commit-hooks infra.
* Check (+fix) ruff lint issues
* Verify Conventional Commit message ([see here](https://www.conventionalcommits.org/))
=> feat: Add pre-commit-hooks

iec_api/data.py
=> fix: Fix calls with `isSuccess`=false despite containing all data

iec_api/const.py
=> fix: Fix wrong parameter order in calls to Billing Invoices

iec_api/const.py, iec_api/data.py, iec_api/iec_client.py, iec_api/models/remote_reading.py
=> fix: Fix RemoteReadingRange call

example.py, pyproject.toml
Downgrade aiohttp dependency for HomeAssistant 2023.12 support 
=> fix: 0.2.0 dependency

pyproject.toml
=> chore: bump to 0.2.1

iec_api/models/contract.py, iec_api/models/device.py, iec_api/models/invoice.py, iec_api/models/meter_reading.py, iec_api/models/remote_reading.py
parse datetime fields as datetime and not str
Manually
=> fix: parse datetime fields as datetime and not str

iec_api/commons.py, iec_api/data.py
=> feat: minor styling fixes

example.py
=> chore: Revert Example ID

iec_api/iec_client.py
When token is valid set `logged_in` = True
Manually
#70
=> fix: Fix creating a client and loading token

pyproject.toml
=> chore: bump to 0.2.3

iec_api/const.py, iec_api/models/invoice.py, iec_api/models/meter_reading.py, iec_api/models/remote_reading.py, pyproject.toml
Localize dates to TimeZone Asia/Jerusalem
=> fix: Localize dates to TimeZone Asia/Jerusalem

example.py, iec_api/commons.py, iec_api/data.py, iec_api/iec_client.py
=> Revert "feat: Generic aiohttp logging"

example.py, iec_api/commons.py, iec_api/data.py, iec_api/iec_client.py
=> feat: Generic aiohttp logging

iec_api/const.py, iec_api/data.py, iec_api/iec_client.py, iec_api/models/efs.py
Add get EFS Messages API
Manually
=> feat: Add get EFS Messages API

iec_api/usage_calculator/calculator.py, pyproject.toml
Cast to `float`
___
Bug fix, Enhancement
___
- Fixed a type error by casting the result of multiplication between `home_rate` and `vat` to `float` in `iec_api/usage_calculator/calculator.py`.
- Updated the project version in `pyproject.toml` from 0.2.14 to 0.2.16 to reflect the new changes.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>calculator.py</strong><dd><code>Fix type error in tariff and rate calculations</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
iec_api/usage_calculator/calculator.py
<li>Cast multiplication results of <code>home_rate</code> and <code>vat</code> to …
=> Fix `unsupported operand type(s) for *: 'float' and 'decimal.Decimal'` in Calculator usage

iec_api/const.py, iec_api/data.py, iec_api/iec_client.py, iec_api/models/account.py, iec_api/models/customer.py, iec_api/models/outages.py, iec_api/usage_calculator/calculator.py
Add Account Outages API 
___
Enhancement, Bug fix
___
- Added new API endpoints and handling for outages in the IEC API.
- Introduced a new data model for outages with appropriate decoding.
- Enhanced the IEC client to fetch outages by account.
- Fixed type handling in usage calculations to prevent type errors.
- Renamed the Account model to CustomerAccount for better clarity in the customer module.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>const.py</strong><dd><code>Add new API URLs for outage handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> feat: Get Account Outages API

Makefile
=> fix: Fix MakeFile

Makefile, iec_api/const.py, iec_api/iec_client.py, iec_api/models/device.py, iec_api/static_data.py, iec_api/usage_calculator/calculator.py, pyproject.toml
Add Distribution and Delivery Tarrifs - parsed from: https://www.iec.co.il/content/tariffs/contentpages/homeelectricitytariff
No tests yet
=> feat: Add Static KVA, Delivery, Distribution and PowerSize prices

iec_api/models/contract.py
=> feat: New Field in Contract object

iec_api/iec_client.py
=> fix: Fix error on missing Masa equipment

.github/workflows/publish.yml, pyproject.toml
new publish mechanism - based on new tag
=> feat: new publish mechanism

iec_api/commons.py, iec_api/data.py, iec_api/iec_client.py, iec_api/login.py, iec_api/masa_api_models/building_options.py, iec_api/masa_api_models/cities.py, iec_api/masa_api_models/equipment.py, iec_api/masa_api_models/lookup.py, iec_api/masa_api_models/order_lookup.py, iec_api/masa_api_models/titles.py, iec_api/masa_api_models/volt_levels.py, iec_api/masa_data.py, iec_api/models/account.py, iec_api/models/contract.py, iec_api/models/contract_check.py, iec_api/models/customer.py, iec_api/models/device.py, iec_api/models/device_identity.py, iec_api/models/device_type.py, iec_api/models/electric_bill.py, iec_api/models/error_response.py, iec_api/models/invoice.py, iec_api/models/jwt.py, iec_api/models/meter_reading.py, iec_api/models/outages.py, iec_api/models/remote_reading.py, iec_api/models/response_descriptor.py, iec_api/models/send_consumption_to_mail.py, tests/commons_test.py
https://github.com/GuyKh/iec-custom-component/issues/206
=> Fix: allow missing fields (Optional)

iec_api/models/invoice.py
=> fix: Fix object ordering

iec_api/models/meter_reading.py
Fix breaking api - as described - https://github.com/GuyKh/iec-custom-component/issues/212
=> fix: Update MeterReading with API changes

iec_api/models/meter_reading.py
https://github.com/GuyKh/iec-custom-component/issues/206
=> fix: IEC API change - Meter Reading optional fields

iec_api/models/customer.py
API Change: CustomerAccount.name+last_name don't return on API
#155
=> fix: API Change: CustomerAccount.name+last_name don't return on API

iec_api/commons.py, iec_api/models/customer.py
=> feat: Include URL in HTTP Debug

example.py, iec_api/iec_client.py, iec_api/login.py, iec_api/models/meter_reading.py
feat: OTP returns the OTP Factor Type
___
Enhancement
___
- Modified OTP functions to return factor type alongside session token
- Updated function signatures and return types for better information flow
- Enhanced user prompts to include factor type information
___
```mermaid
flowchart LR
A["send_otp_code()"] --> B["Returns session token + factor type"]
B --> C["first_login()"]
B --> D["verify_otp_code()"]
C --> E["Enhanced user prompt with factor type"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>login.py</strong><dd><code>Enhanced OTP functions to return factor type</code>&nbsp; …
=> feat: OTP returns the OTP Factor Type
